version: '3'
services:
  app:
    build:
      context: .
    command: npm run docker:start
    ports:
      - "3000:80"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - /tmp/redis:/data
    networks:
      - mynetwork

networks:
  mynetwork:
